/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String args[]) {
		Library lib = new Library();
		if(lib.someLibraryMethod()) {
			System.out.println("Commit and Push.");
		}
		System.out.println("When there is a fire.");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
